version = 1
SPDX-PackageName = "technologydata"
SPDX-PackageSupplier = "The technology-data authors"
SPDX-PackageDownloadLocation = "https://github.com/pypsa/technology-data"

[[annotations]]
path = ["uv.lock", ".readthedocs.yaml", "mkdocs.yaml", "docs/*", "docs/*/*", "docs/*/*/*", "docs/*/*/*/*", ]
SPDX-FileCopyrightText = "The technology-data authors"
SPDX-License-Identifier = "MIT"


[[annotations]]
path = ["test/test_data/*/*", "test/test_data/*/*/*"]
SPDX-FileCopyrightText = "The technology-data authors"
SPDX-License-Identifier = "CC-BY-4.0"
