version = 1
SPDX-PackageName = "technologydata"
SPDX-PackageSupplier = "The technology-data authors"
SPDX-PackageDownloadLocation = "https://github.com/pypsa/technology-data"

[[annotations]]
path = "uv.lock"
precedence = "override"
SPDX-FileCopyrightText = "The technology-data authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "technologydata/utils/pydeflate/wb_*.parquet"
precedence = "override"
SPDX-FileCopyrightText = "The technology-data authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "test/test_data/*/*"
precedence = "override"
SPDX-FileCopyrightText = "The technology-data authors"
SPDX-License-Identifier = "MIT"
